[package]
name = "oxeylyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
fastrand = "1.6.0"
rayon = "1.5.1"
file-chunker = "0.1.1"
anyhow = "1.0.57"
unicode-normalization = "0.1.19"
indexmap = {version = "1.8.1", features = ["serde"]}
fxhash = "0.2.1"
indicatif = {version = "0.16.2", features = ["rayon"]}
toml = "0.5.9"
ansi_rgb = {git = "https://github.com/O-X-E-Y/ansi_rgb"}
lazy_static = "1.4.0"
smallmap = "1.3.4"