inherits = ["default"]

letters_to_lowercase = "éà"

[multiple]
uppercase_versions = true
list = [
    ["ç", "*c"],
    ["œ", "* "],

    ["â", "*a"],
    ["ê", "*e"],
    ["î", "*i"],
    ["ô", "*o"],
    ["û", "*u"],

    ["è", "* e"],
    ["ì", "* i"],
    ["ò", "* o"],
    ["ù", "* u"],

    ["á", "* a"],
    ["í", "* i"],
    ["ó", "* o"],
    ["ú", "* u"],
    
    ["ä", "* a"],
    ["ë", "* e"],
    ["ï", "* i"],
    ["ö", "* o"],
    ["ü", "* u"]
]
