inherits = ["default_punct"]

keep = "ㅣㅡㅜㅏㅊㅈㅅㅂㅁㄹㄷㄴㄱㅇㅋㅌㅍㅐㅑㅓㅕㅗㅎㅔㅛㅠ"

[one_to_one]
from = "ㄲㄸㅆㅃㅉㅒㅖ"
to = "ㄱㄷㅅㅂㅈㅐㅔ"

[multiple]
list = [
    ["ㄳ", "ㄱㅅ"],
    ["ㅥ", "ㄴㄴ"],
    ["ㅦ", "ㄴㄷ"],
    ["ㅧ", "ㄴㅅ"],
    ["ㄵ", "ㄴㅈ"],
    ["ㄶ", "ㄴㅎ"],
    ["ㄺ", "ㄹㄱ"],
    ["ㅩ", "ㄹㄱㅅ"],
    ["ㅪ", "ㄹㄷ"],
    ["ㄻ", "ㄹㅁ"],
    ["ㄼ", "ㄹㅂ"],
    ["ㅫ", "ㄹㅂㅅ"],
    ["ㄽ", "ㄹㅅ"],
    ["ㄾ", "ㄹㅌ"],
    ["ㄿ", "ㄹㅍ"],
    ["ㅀ", "ㄹㅎ"],
    ["ㅮ", "ㅁㅂ"],
    ["ㅯ", "ㅁㅅ"],
    ["ㅲ", "ㅂㄱ"],
    ["ㅳ", "ㅂㄷ"],
    ["ㅄ", "ㅂㅅ"],
    ["ㅴ", "ㅂㅅㄱ"],
    ["ㅵ", "ㅂㅅㄷ"],
    ["ㅶ", "ㅂㅈ"],
    ["ㅷ", "ㅂㅌ"],
    ["ㅹ", "ㅂㅂ"],
    ["ㅺ", "ㅅㄱ"],
    ["ㅻ", "ㅅㄴ"],
    ["ㅼ", "ㅅㄷ"],
    ["ㅽ", "ㅅㅂ"],
    ["ㅾ", "ㅅㅈ"],
    ["ㆀ", "ㅇㅇ"],
    ["ㆄ", "ㅍ"],
    ["ㆅ", "ㅎㅎ"],
    ["ㅘ", "ㅗㅏ"],
    ["ㅙ", "ㅗㅐ"],
    ["ㅚ", "ㅗㅣ"],
    ["ㆇ", "ㅛㅑ"],
    ["ㆈ", "ㅛㅐ"],
    ["ㆉ", "ㅛㅣ"],
    ["ㅝ", "ㅜㅓ"],
    ["ㅞ", "ㅜㅔ"],
    ["ㅟ", "ㅜㅣ"],
    ["ㆊ", "ㅠㅖ"],
    ["ㆋ", "ㅠㅖ"],
    ["ㆌ", "ㅠㅣ"],
    ["ㅢ", "ㅡㅣ"],
    ["ㅸ", "ㅂ"],
    ["ㅱ", "ㅁ"]
]