inherits = ["default"]

[multiple]
uppercase_versions = true
list = [
    ['â', "*a"],
    ['ê', "*e"],
    ['î', "*i"],
    ['ô', "*o"],
    ['û', "*u"],
    ['ŵ', "*w"],
    ['ŷ', "*y"]
]