pins = """
..... .....
..... .....
..... .....
"""

[defaults]
language = "english"
trigram_precision = 1000
keyboard_type = "ansi angle"
max_cores = 32

[weights]
heatmap = 1.65
fspeed = 18.0
lateral_penalty = 1.0
dsfb_ratio = 0.11
scissors = 4.5
lsbs = 1.5
inrolls = 1.5
outrolls = 1.35
onehands = 0.9
alternates = 0.9
alternates_sfs = 0.6
redirects = 1.4
redirects_sfs = 2.2
bad_redirects = 4.5
bad_redirects_sfs = 6.0

[weights.max_finger_use]
penalty = 2.5
pinky = 9.0
ring = 14.0
middle = 20.0
index = 20.0