[package]
name = "oxeylyzer-core"
version = "0.1.0"
authors = ["O_X_E_Y <lucoerlemans37@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
nanorand = "0.7.0"
rayon = "1.5.1"
file-chunker = "0.1.1"
anyhow = "1.0.57"
indexmap = { version = "1.8.1", features = ["serde"] }
fxhash = "0.2.1"
toml = "0.5.9"
smartstring = { git = "https://github.com/O-X-E-Y/smartstring", features = ["serde"] }
arrayvec = "0.7.2"
once_cell = "1.16.0"
ansi_rgb = { git = "https://github.com/O-X-E-Y/ansi_rgb" }